### ISSUE TITLE
Bugs in dataset

### ISSUE THREAD

**Issue by martef** [anders-kolstad/peatmoss_and_ditches#3]
- [x] 1. Dates for half of pins spring 2019 are set to 05.10.2019, not 10.05.2019. They need to be corrected.
- [x] 2. Many dates for 2020 are wrongly labelled 2022 in the dates column. This is for quadrat 1 to 9 in spring.
- [x] 3. The link in the github logo on the webpage leads to the NINA template page, update the link 
- [x] 4. Remove all pins with 'old' from spring
- [x] 5. 'New' only means new pin inserted at that specific point in time, meaning if the pin is new in spring then it can be overlooked, while if it is new in fall, then that data point cannot be compared with the same year's spring data
- [x] 6. The new pins from 2018 and 2019 don't have the notations of plot-number, pin-number, and treatment included. These must be updated.

**Comment by anders-kolstad** [comment]
- [x] Combine pin position in 2018. Marte started with dual measuremenst that fall.
- [x] Carry the species column
- [x] Combine W1 and W2, and E1 and E2

**Comment by anders-kolstad** [comment]
- [x] It appears one ID can have more treatments. See for example `ID_num == 28.80` 

I found that 13 plots changed treatment from Hollow in 2021 to Edge in 2022. I did not change the data in anyway, but the plot IDs are printed at the bottom of the data exploration chapter.

**Comment by anders-kolstad** [comment]
Most of these things were solved in #4 , but there are still some NA that I will try and sort out
